### ISSUE TITLE
Pull Request template does not show up 

### ISSUE THREAD

**Issue by TimoWielink** [Call-for-Code/ClusterDuck-Protocol#181]
**Describe the bug**
@krook Added a PR template but it does not show up when you make a Pull Request.

**To Reproduce**
1. Make a Pull request

**Expected behavior**
A template is shown with what kind of information you need to provide

**Additional context**
https://github.com/Call-for-Code/ClusterDuck-Protocol/tree/master/.github/PULL_REQUEST_TEMPLATE

**Comment by krook** [comment]
Double-checking the [docs](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository), I see that the approach I took supports multiple templates, but you might have to supply a query parameter to use it. 

I think the right approach is instead to `git mv` the `pull_request_template.md` file up and out of the `PULL_REQUEST_TEMPLATE` directory so that it's the single default template.
